version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=store
    hostname: postgreshost
    container_name: postgresql-local
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: my_store-postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 5433:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=car@los.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
networks:
  default:
    name: test-network
    external: true
