version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=store
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=car@los.com
      - PGADMIN_DEFAULT_PASSWORD=root